spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recommender_system_db
    username: bishoy
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 120000
      maximum-pool-size: 50
  jpa:
    show-sql: true