spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/recommender_system_db}
    username: ${DATABASE_USERNAME:bishoy}
    password: ${DATABASE_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 120000
      maximum-pool-size: 50
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /
    url: /movie-api.yaml